version: '3.3'
services:
  gateway:
    image: traefik:v2.2.7
    command: --entrypoints.web.address=:80 --providers.docker.exposedbydefault=false --providers.docker --api #--log.level=DEBUG
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
  mainservice:
    build:
      context: mainservice
      dockerfile: src/main/docker/Dockerfile.jvm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mainservice.rule=Host(`localhost`) && PathPrefix(`/currencies`)"
      - "traefik.http.routers.mainservice.entrypoints=web"
      - "traefik.http.routers.mainservice.middlewares=strip-currencies-prefix@docker"
      - "traefik.http.middlewares.strip-currencies-prefix.stripprefix.prefixes=/currencies"
  alphavantage:
    build:
      context: alphavantage
      dockerfile: src/main/docker/Dockerfile.jvm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alphavantage.rule=PathPrefix(`/service/av`)"
      - "traefik.http.routers.alphavantage.entrypoints=web"
      - "traefik.http.routers.alphavantage.middlewares=strip-service-prefix@docker"
      - "traefik.http.middlewares.strip-service-prefix.stripprefix.prefixes=/service"
      # uncomment this line if u use the traefik.yml
      - "traefik.http.services.alphavantage.loadbalancer.server.port=8080"
      # if not using traefik.yml set this value to -1, so alphavantage will be the used Endpoint
      - "traefik.http.services.alphavantage.loadbalancer.responseforwarding.flushinterval=10"
      - "traefik.http.services.alphavantage.loadbalancer.healthcheck.path=/av/health"
      - "traefik.http.services.alphavantage.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.alphavantage.loadbalancer.healthcheck.timeout=3s"
  wahrungsrechner:
    build:
      context: wahrungsrechner
      dockerfile: src/docker/Dockerfile.jvm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wahrungsrechner.rule=PathPrefix(`/service/wr`)"
      - "traefik.http.routers.wahrungsrechner.entrypoints=web"
      - "traefik.http.routers.wahrungsrechner.middlewares=strip-service-prefix@docker"
      - "traefik.http.middlewares.strip-service-prefix.stripprefix.prefixes=/service"
      #uncomment this line if u use the traefik.yml
      - "traefik.http.services.wahrungsrechner.loadbalancer.server.port=8080"
      # if not using traefik.yml set this value to -1, so alphavantage will be the used Endpoint
      - "traefik.http.services.wahrungsrechner.loadbalancer.responseforwarding.flushinterval=10"
      - "traefik.http.services.wahrungsrechner.loadbalancer.healthcheck.path=wr/health"
      - "traefik.http.services.wahrungsrechner.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.wahrungsrechner.loadbalancer.healthcheck.timeout=3s"